catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
minimumReleaseAgeExclude:
  - "@roman-mik/kapa-core@0.5.0 || 0.6.0"
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
